#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun May 17 15:50:22 IST 2026
# SW Build 6403652 on Thu Mar 19 13:47:00 MDT 2026
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L secureip --snapshot testbench_behav work.testbench -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L secureip --snapshot testbench_behav work.testbench -log elaborate.log

